### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sparador** [nates/DiscordVerification#12]
I setted up the variable, it start, it say it's working but don't send the capcha when a use join.
I received the answer on what is supposed to do 
"You need to fill out the variable, then when a user joins your server they will have to solve a ReCAPTCHA."
It isn't doing it.

**Comment by nates** [comment]
You must have Direct messages off or your variables are wrong.

**Comment by sparador** [comment]
all varianbles right and dm on... idk.. the role should be setted by the role id ig, if i'm not wrong on this, idk...

**Comment by nates** [comment]
You may need to give it the track server members intent in your application.
