### ISSUE TITLE
Unable To Go To The Captcha site.

### ISSUE THREAD

**Issue by LCJE** [nates/DiscordVerification#2]
Hello! first of all i'd like to say that it is easy to setup and i had no problems starting the bot. An issue did start when I tried to testing by getting an alt to test it, once i clicked on the link it came up with this. If you could help that would be great, thanks

It would be preferable if you were to contact me via Discord, my @ is LCJE#9999
![image](https://user-images.githubusercontent.com/59238052/93691717-d2ae6a00-fb2c-11ea-8ee8-cd0305c08a19.png)

**Comment by nates** [comment]
Add your repl.it domain into the variables.js file.
