### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Tamim-ul-Alam-Chy** [nates/DiscordVerification#4]
Please make a youtube tutorial.

**Comment by Tamim-ul-Alam-Chy** [comment]
i have a problem with the link

**Comment by nates** [comment]
I won't be making a youtube tutorial, but you need to start the program by running 'node .' on the command line.

**Comment by Tamim-ul-Alam-Chy** [comment]
can i have to host the bot and website in one pc?

**Comment by nates** [comment]
Yes, you must host it all on one pc.
